### ISSUE TITLE
Error when ./test.sh

### ISSUE THREAD

**Issue by Barnonewdm** [node21challenge/node21_detection_baseline#3]
```
loading the model.pth file :
Traceback (most recent call last):
  File "process.py", line 228, in <module>
    Noduledetection(parsed_args.input_dir, parsed_args.output_dir, retest=parsed_args.retest).process()
  File "process.py", line 57, in __init__
    map_location=self.device,
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
./test.sh: line 15: python3: command not found
cat: /output/nodules.json: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/output/nodules.json'
Expected output was not found...
noduledetection-output
```

**Comment by Barnonewdm** [comment]
`Traceback (most recent call last):
  File "process.py", line 228, in <module>
    Noduledetection(parsed_args.input_dir, parsed_args.output_dir, retest=parsed_args.retest).process()
  File "/home/algorithm/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 181, in process
    self.load()
  File "/home/algorithm/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 126, in load
    file_filter=fltr,
  File "/home/algorithm/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 158, in _load_cases
    f"Could not load any files in {folder} with " f"{file_loader}."
evalutils.exceptions.FileLoaderError: Could not load any files in /input with <evalutils.io.SimpleITKLoader object at 0x7f192a0776d0>.`

Anyone find the solution?

**Comment by ckolluru** [comment]
I'm facing an issue when running ./test.sh as well.

> dirname: invalid option -- 'b'
> Try 'dirname --help' for more information.
> dirname: invalid option -- 'b'
> Try 'dirname --help' for more information.
> [+] Building 1.2s (18/18) FINISHED
>  => [internal] load build definition from Dockerfile                                                               0.0s
>  => => transferring dockerfile: 38B                                                                                0.0s
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 2B                                                                                    0.0s
>  => [internal] load metadata for docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime                           0.9s
>  => [ 1/13] FROM docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime@sha256:e04020e1b6cc744659c70f5afdc0ab602  0.0s
>  => [internal] load build context                                                                                  0.1s
>  => => transferring context: 745B                                                                                  0.0s
>  => CACHED [ 2/13] RUN groupadd -r algorithm && useradd -m --no-log-init -r -g algorithm algorithm                 0.0s
>  => CACHED [ 3/13] RUN mkdir -p /opt/algorithm /input /output     && chown algorithm:algorithm /opt/algorithm /in  0.0s
>  => CACHED [ 4/13] WORKDIR /opt/algorithm                                                                          0.0s
>  => CACHED [ 5/13] RUN python -m pip install --user -U pip                                                         0.0s
>  => CACHED [ 6/13] RUN  pip install --upgrade pip                                                                  0.0s
>  => CACHED [ 7/13] COPY --chown=algorithm:algorithm requirements.txt /opt/algorithm/                               0.0s
>  => CACHED [ 8/13] COPY --chown=algorithm:algorithm entrypoint.sh /opt/algorithm/                                  0.0s
>  => CACHED [ 9/13] COPY --chown=algorithm:algorithm model.pth /opt/algorithm/                                      0.0s
>  => CACHED [10/13] COPY --chown=algorithm:algorithm resnet50-19c8e357.pth  /home/algorithm/.cache/torch/hub/check  0.0s
>  => CACHED [11/13] COPY --chown=algorithm:algorithm training_utils /opt/algorithm/training_utils                   0.0s
>  => CACHED [12/13] RUN python -m pip install --user -r requirements.txt                                            0.0s
>  => CACHED [13/13] COPY --chown=algorithm:algorithm process.py postprocessing.py /opt/algorithm/                   0.0s
>  => exporting to image                                                                                             0.1s
>  => => exporting layers                                                                                            0.0s
>  => => writing image sha256:0cc0a88b166779bf5eb43b44dbaefd2467f9252f12fc6dc9191f46f7254cbf16                       0.0s
>  => => naming to docker.io/library/noduledetector                                                                  0.0s
> noduledetection-output
> parameters are
> usage: process.py [-h] [--train] [--retrain] [--retest] input_dir output_dir
> process.py: error: unrecognized arguments:
> cat: /output/nodules.json: No such file or directory
> Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> FileNotFoundError: [Errno 2] No such file or directory: '/output/nodules.json'
> Expected output was not found...
> noduledetection-output

**Comment by Barnonewdm** [comment]
The test.bat works in Windows. But test.sh cannot work well in Linux.

**Comment by ckolluru** [comment]
Hmm, are any changes required to run it? Apart from the typo in the dockerfile? I still see some errors when running test.bat on Windows.

> D:\node21-pycharm\node21_detection_baseline>call .\build.bat
> 
> D:\node21-pycharm\node21_detection_baseline>docker build -t noduledetection .
> [+] Building 1.0s (18/18) FINISHED
>  => [internal] load build definition from Dockerfile                                                               0.0s
>  => => transferring dockerfile: 32B                                                                                0.0s
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 2B                                                                                    0.0s
>  => [internal] load metadata for docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime                           0.8s
>  => [internal] load build context                                                                                  0.0s
>  => => transferring context: 424B                                                                                  0.0s
>  => [ 1/13] FROM docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime@sha256:e04020e1b6cc744659c70f5afdc0ab602  0.0s
>  => CACHED [ 2/13] RUN groupadd -r algorithm && useradd -m --no-log-init -r -g algorithm algorithm                 0.0s
>  => CACHED [ 3/13] RUN mkdir -p /opt/algorithm /input /output     && chown algorithm:algorithm /opt/algorithm /in  0.0s
>  => CACHED [ 4/13] WORKDIR /opt/algorithm                                                                          0.0s
>  => CACHED [ 5/13] RUN python -m pip install --user -U pip                                                         0.0s
>  => CACHED [ 6/13] RUN  pip install --upgrade pip                                                                  0.0s
>  => CACHED [ 7/13] COPY --chown=algorithm:algorithm requirements.txt /opt/algorithm/                               0.0s
>  => CACHED [ 8/13] COPY --chown=algorithm:algorithm entrypoint.sh /opt/algorithm/                                  0.0s
>  => CACHED [ 9/13] COPY --chown=algorithm:algorithm model.pth /opt/algorithm/                                      0.0s
>  => CACHED [10/13] COPY --chown=algorithm:algorithm resnet50-19c8e357.pth  /home/algorithm/.cache/torch/hub/check  0.0s
>  => CACHED [11/13] COPY --chown=algorithm:algorithm training_utils /opt/algorithm/training_utils                   0.0s
>  => CACHED [12/13] RUN python -m pip install --user -r requirements.txt                                            0.0s
>  => CACHED [13/13] COPY --chown=algorithm:algorithm process.py postprocessing.py /opt/algorithm/                   0.0s
>  => exporting to image                                                                                             0.1s
>  => => exporting layers                                                                                            0.0s
>  => => writing image sha256:dc2a3418f3a31cf3726bbef69c74364bce71a51568b724e254c0d3e6c52752ab                       0.0s
>  => => naming to docker.io/library/noduledetection                                                                 0.0s
> 
> Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
> 
> D:\node21-pycharm\node21_detection_baseline>docker volume create noduledetection-output
> noduledetection-output
> 
> D:\node21-pycharm\node21_detection_baseline>docker run --rm --memory=8g -v D:\node21-pycharm\node21_detection_baseline\\test\:/input/ -v D:\node21-pycharm\node21_detection_baseline\\output\:/output/ noduledetection
> parameters are
> usage: process.py [-h] [--train] [--retrain] [--retest] input_dir output_dir
> process.py: error: unrecognized arguments:
> 
> D:\node21-pycharm\node21_detection_baseline>docker run --rm -v D:\node21-pycharm\node21_detection_baseline\\output\:/output/ python:3.7-slim cat /output/results.json   | python -m json.tool
> cat: /output/results.json: No such file or directory
> Expecting value: line 1 column 1 (char 0)
> 
> D:\node21-pycharm\node21_detection_baseline>docker run --rm -v D:\node21-pycharm\node21_detection_baseline\\output\:/output/ -v D:\node21-pycharm\node21_detection_baseline\\test\:/input/ python:3.7-slim python -c "import json, sys; f1 = json.load(open('/output/results.json')); f2 = json.load(open('/input/expected_output.json')); sys.exit(f1 != f2);"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> FileNotFoundError: [Errno 2] No such file or directory: '/output/results.json'
> 
> D:\node21-pycharm\node21_detection_baseline>if 1 == 0 (echo "Tests successfully passed..." )
> 
> D:\node21-pycharm\node21_detection_baseline>else
> 'else' is not recognized as an internal or external command,
> operable program or batch file.
> 
> D:\node21-pycharm\node21_detection_baseline>(echo "Expected output was not found..." )
> "Expected output was not found..."
> 
> D:\node21-pycharm\node21_detection_baseline>docker volume rm noduledetection-output
> noduledetection-output
> 
> 
> 
>
